// ====== DATA ======
const CROPS = [
  { id:'wheat', emoji:'🌾', season:'rabi', nameHi:'गेहूं', nameEn:'Wheat', nameBh:'गोंहू',
    soil:'दोमट मिट्टी, pH 6-7', irrigation:'सिंचाई 5-6 बार, पहली 20-25 दिन पर',
    fertilizer:[{stage:'बुवाई',detail:'DAP 50 kg/एकड़ + यूरिया 25 kg'},{stage:'30 दिन',detail:'यूरिया 30 kg, पानी के साथ'},{stage:'60 दिन',detail:'पोटाश 20 kg + यूरिया 20 kg'}],
    pests:[{name:'गेरुआ रोग',treatment:'Propiconazole 25% EC दवाई का 0.1% घोल छिड़कें'},{name:'चूहा नुकसान',treatment:'जिंक फॉस्फाइड चारे का उपयोग करें'}],
    sowMonth:'नवंबर - दिसंबर', harvestMonth:'मार्च - अप्रैल' },
  { id:'rice', emoji:'🌾', season:'kharif', nameHi:'धान', nameEn:'Rice', nameBh:'धान',
    soil:'चिकनी/भारी मिट्टी, अधिक जल धारण', irrigation:'खेत में 5 cm पानी बनाए रखें',
    fertilizer:[{stage:'रोपाई',detail:'DAP 50 kg + पोटाश 30 kg'},{stage:'25 दिन',detail:'यूरिया 35 kg'},{stage:'45 दिन',detail:'यूरिया 25 kg'}],
    pests:[{name:'तना छेदक',treatment:'Carbofuran 3G 7 kg/एकड़ डालें'},{name:'ब्लास्ट रोग',treatment:'Tricyclazole 75% WP का 0.06% छिड़काव'}],
    sowMonth:'जून - जुलाई', harvestMonth:'अक्टूबर - नवंबर' },
  { id:'cotton', emoji:'🌿', season:'kharif', nameHi:'कपास', nameEn:'Cotton', nameBh:'कपास',
    soil:'काली दोमट मिट्टी, गहरी जड़ वाली', irrigation:'15-20 दिन अंतर पर, फूल पर नियमित',
    fertilizer:[{stage:'बुवाई',detail:'SSP 75 kg + पोटाश 25 kg'},{stage:'40 दिन',detail:'यूरिया 40 kg'},{stage:'फूल',detail:'यूरिया 20 kg + बोरान 1 kg'}],
    pests:[{name:'बॉलवर्म',treatment:'Spinosad 45 SC 0.3 ml/L का छिड़काव'},{name:'सफेद मक्खी',treatment:'Imidacloprid 17.8 SL 0.5 ml/L'}],
    sowMonth:'मई - जून', harvestMonth:'नवंबर - फरवरी' },
  { id:'sugarcane', emoji:'🎋', season:'zaid', nameHi:'गन्ना', nameEn:'Sugarcane', nameBh:'ईख',
    soil:'दोमट, अच्छी जल निकासी, pH 6.5-7.5', irrigation:'पहले महीने हर 8 दिन, बाद में 15 दिन',
    fertilizer:[{stage:'रोपाई',detail:'FYM 20 t/ha + उर्वरक'},{stage:'30 दिन',detail:'यूरिया 60 kg/एकड़'},{stage:'90 दिन',detail:'यूरिया 60 kg + पोटाश 30 kg'}],
    pests:[{name:'अगेती गांठ सड़न',treatment:'Carbendazim 50 WP 2g/L छिड़काव'},{name:'दीमक',treatment:'Chlorpyrifos 20 EC से बीज उपचार'}],
    sowMonth:'फरवरी - मार्च', harvestMonth:'दिसंबर - मार्च' },
  { id:'tomato', emoji:'🍅', season:'zaid', nameHi:'टमाटर', nameEn:'Tomato', nameBh:'टमाटर',
    soil:'दोमट, अच्छी जल निकासी, pH 6-7', irrigation:'ड्रिप या फव्वारा, 3-4 दिन अंतर',
    fertilizer:[{stage:'रोपण',detail:'FYM 15 t/ha + NPK 10:26:26 @ 50 kg'},{stage:'20 दिन',detail:'यूरिया 20 kg'},{stage:'फूल',detail:'पोटाश 25 kg + कैल्शियम नाइट्रेट'}],
    pests:[{name:'पत्ती मोड़क विषाणु',treatment:'Imidacloprid छिड़काव, रोगी पौधे हटाएं'},{name:'अगेती झुलसा',treatment:'Mancozeb 75 WP 2.5 g/L छिड़काव'}],
    sowMonth:'जून-जुलाई / नवंबर', harvestMonth:'3-4 महीने बाद' },
  { id:'onion', emoji:'🧅', season:'rabi', nameHi:'प्याज', nameEn:'Onion', nameBh:'प्याज',
    soil:'दोमट, अच्छी जल निकासी', irrigation:'7-10 दिन अंतर, परिपक्वता पर बंद',
    fertilizer:[{stage:'रोपाई',detail:'DAP 40 kg + पोटाश 40 kg'},{stage:'30 दिन',detail:'यूरिया 35 kg'},{stage:'50 दिन',detail:'पोटाश 20 kg'}],
    pests:[{name:'थ्रिप्स',treatment:'Spinosad 45SC 0.3 ml/L'},{name:'बैंगनी धब्बा',treatment:'Mancozeb या Iprodione छिड़काव'}],
    sowMonth:'अक्टूबर - नवंबर', harvestMonth:'मार्च - अप्रैल' },
  { id:'potato', emoji:'🥔', season:'rabi', nameHi:'आलू', nameEn:'Potato', nameBh:'आलू',
    soil:'रेतीली दोमट, ढीली, pH 5.5-6.5', irrigation:'बुवाई के तुरंत बाद, फिर 10-15 दिन',
    fertilizer:[{stage:'बुवाई',detail:'DAP 60 kg + MOP 50 kg + यूरिया 30 kg'},{stage:'30 दिन',detail:'यूरिया 40 kg मिट्टी चढ़ाते समय'}],
    pests:[{name:'माहू (एफिड)',treatment:'Imidacloprid 0.5 ml/L'},{name:'झुलसा रोग',treatment:'Metalaxyl + Mancozeb हर 7 दिन'}],
    sowMonth:'अक्टूबर - नवंबर', harvestMonth:'जनवरी - फरवरी' },
  { id:'maize', emoji:'🌽', season:'kharif', nameHi:'मक्का', nameEn:'Maize', nameBh:'मकई',
    soil:'दोमट से बलुई दोमट, pH 6-7.5', irrigation:'घुटन का प्रतिरोधी, फूल पर आवश्यक',
    fertilizer:[{stage:'बुवाई',detail:'DAP 50 kg + पोटाश 25 kg'},{stage:'25 दिन',detail:'यूरिया 40 kg'},{stage:'45 दिन',detail:'यूरिया 30 kg'}],
    pests:[{name:'फॉल आर्मीवर्म',treatment:'Emamectin Benzoate 5SG 0.4 g/L'},{name:'तना छेदक',treatment:'Chlorpyrifos कणिका डालें'}],
    sowMonth:'जून - जुलाई', harvestMonth:'सितंबर - अक्टूबर' },
];

const MANDI_DATA = [
  {mandi:'वाराणसी मंडी', district:'varanasi', crop:'wheat', cropHi:'गेहूं', min:2050, max:2280, avg:2165},
  {mandi:'लखनऊ मंडी', district:'lucknow', crop:'wheat', cropHi:'गेहूं', min:2080, max:2300, avg:2190},
  {mandi:'आगरा मंडी', district:'agra', crop:'potato', cropHi:'आलू', min:800, max:1100, avg:950},
  {mandi:'कानपुर मंडी', district:'kanpur', crop:'rice', cropHi:'धान', min:1800, max:2100, avg:1950},
  {mandi:'प्रयागराज मंडी', district:'allahabad', crop:'onion', cropHi:'प्याज', min:1200, max:1800, avg:1500},
  {mandi:'झांसी मंडी', district:'jhansi', crop:'maize', cropHi:'मक्का', min:1500, max:1750, avg:1625},
  {mandi:'गोरखपुर मंडी', district:'gorakhpur', crop:'sugarcane', cropHi:'गन्ना', min:350, max:380, avg:365},
  {mandi:'मथुरा मंडी', district:'mathura', crop:'wheat', cropHi:'गेहूं', min:2060, max:2250, avg:2155},
];

const QUESTIONS = [
  {id:1, title:'गेहूं की पत्तियां पीली क्यों हो रही हैं?', crop:'wheat', cropHi:'गेहूं', district:'वाराणसी', answers:5, votes:23, desc:'मेरे खेत में गेहूं की पत्तियां 30 दिन बाद पीली पड़ने लगी हैं। क्या करें?',
    answersList:[{text:'यह नाइट्रोजन की कमी के कारण है। 25 kg यूरिया प्रति एकड़ डालें और 2 लीटर पानी के साथ छिड़काव करें।',expert:true,author:'डॉ. रमेश यादव, कृषि विशेषज्ञ',time:'2 घंटे पहले'},{text:'मुझे भी यही समस्या थी, यूरिया डालने से ठीक हो गया।',expert:false,author:'सुरेश पटेल, किसान',time:'5 घंटे पहले'}]},
  {id:2, title:'धान में कीड़े लग गए हैं, क्या दवाई डालें?', crop:'rice', cropHi:'धान', district:'लखनऊ', answers:3, votes:15, desc:'धान के पौधे में तना छेदक कीड़े दिख रहे हैं, पत्तियां मुड़ रही हैं।',
    answersList:[{text:'Carbofuran 3G दवाई 7 kg/एकड़ की दर से हल्की सिंचाई के साथ डालें।',expert:true,author:'डॉ. सीमा सिंह, कृषि वैज्ञानिक',time:'1 दिन पहले'}]},
  {id:3, title:'आलू में झुलसा रोग का प्रकोप है', crop:'potato', cropHi:'आलू', district:'आगरा', answers:7, votes:31, desc:'आलू की पत्तियों पर भूरे धब्बे आ गए हैं और पौधे सूख रहे हैं।',
    answersList:[{text:'Metalaxyl + Mancozeb का छिड़काव हर 7 दिन पर करें। रोगी पत्तियां हटा दें।',expert:true,author:'डॉ. अमित गुप्ता',time:'3 दिन पहले'},{text:'Dithane M-45 भी काम करती है।',expert:false,author:'राजू किसान',time:'3 दिन पहले'}]},
  {id:4, title:'टमाटर के फल फट रहे हैं, कारण क्या है?', crop:'tomato', cropHi:'टमाटर', district:'गोरखपुर', answers:4, votes:18, desc:'टमाटर के फल पकते समय फट जाते हैं।',
    answersList:[{text:'पानी की असमान सिंचाई मुख्य कारण है। नियमित और एक समान सिंचाई करें। कैल्शियम नाइट्रेट का छिड़काव करें।',expert:true,author:'कृषि सलाहकार',time:'1 दिन पहले'}]},
];

const NOTIFICATIONS = [
  {icon:'📈', title:'गेहूं भाव अलर्ट', desc:'वाराणसी मंडी में गेहूं ₹2280/क्विंटल – उच्च भाव!', time:'अभी', unread:true},
  {icon:'⛈️', title:'मौसम चेतावनी', desc:'कल भारी बारिश की संभावना – फसल सुरक्षित रखें', time:'2 घंटे पहले', unread:true},
  {icon:'🚚', title:'ट्रांसपोर्ट अपडेट', desc:'आपकी बुकिंग स्वीकार हो गई – ट्रक रास्ते में है', time:'4 घंटे पहले', unread:true},
  {icon:'💬', title:'नया जवाब', desc:'आपके सवाल का जवाब डॉ. रमेश यादव ने दिया', time:'कल', unread:false},
];

const DISEASES = [
  {name:'पत्ती झुलसा रोग (Leaf Blight)', icon:'🍂', confidence:82, treatments:['Mancozeb 75 WP 2.5 g/L पानी में घोलकर छिड़काव करें','रोगग्रस्त पत्तियां तोड़कर नष्ट करें','खेत में पानी जमा न होने दें','7 दिन बाद दोबारा छिड़काव करें']},
  {name:'चूर्णिल फफूंदी (Powdery Mildew)', icon:'⬜', confidence:76, treatments:['Karathane (Dinocap) 0.1% घोल का छिड़काव','सल्फर WP 3 g/L का उपयोग करें','हवादार जगह पर फसल उगाएं']},
  {name:'तना गलन रोग (Stem Rot)', icon:'🟫', confidence:71, treatments:['Carbendazim 50 WP 1 g/L का छिड़काव','जड़ों के पास जल निकासी सुधारें','रोगी पौधे उखाड़ कर जलाएं']},
];

const TRANSLATIONS = {
  hi: {
    nav_home:'होम', nav_crop:'फसल सूची', nav_community:'समुदाय', nav_mandi:'मंडी भाव', nav_transport:'परिवहन',
    hero_title:'AgroMitra – आपका डिजिटल कृषि साथी',
    hero_desc:'फसल जानकारी, मंडी भाव, विशेषज्ञ सलाह और परिवहन सहायता – सब एक जगह',
    search_placeholder:'फसल, मंडी या सवाल खोजें...', search_btn:'खोजें',
    today_dashboard:'आज का डैशबोर्ड', weather:'आज का मौसम', best_price:'आज का सर्वश्रेष्ठ भाव',
    my_transport:'मेरी परिवहन बुकिंग', community_answers:'नए जवाब',
    see_all_rates:'सभी भाव देखें →', track_transport:'ट्रैक करें →', see_community:'समुदाय देखें →',
    popular_crops:'लोकप्रिय फसलें', crop_library:'🌾 फसल सूची', all:'सभी', kharif:'खरीफ', rabi:'रबी', zaid:'जायद',
    crop_search_placeholder:'फसल का नाम खोजें...',
    community_qa:'💬 किसान समुदाय', ask_question:'+ सवाल पूछें',
    all_crops:'सभी फसलें', latest:'नवीनतम', most_answered:'सबसे ज्यादा जवाब',
    ask_question_title:'नया सवाल पूछें', question_title_label:'सवाल का शीर्षक *',
    select_crop_label:'फसल चुनें *', district_label:'जिला *', description_label:'विवरण',
    upload_image_label:'फोटो अपलोड (वैकल्पिक)', submit_question:'सवाल दर्ज करें',
    mandi_rates:'📊 मंडी भाव', all_districts:'सभी जिले',
    mandi_name:'मंडी का नाम', min_price:'न्यूनतम भाव', max_price:'अधिकतम भाव', avg_price:'औसत भाव',
    price_trend:'पिछले 7 दिनों का भाव', set_alert:'🔔 भाव अलर्ट सेट करें',
    set_price_alert:'भाव अलर्ट सेट करें', alert_price_label:'अलर्ट भाव (₹/क्विंटल)', save_alert:'अलर्ट सेव करें',
    transport_request:'🚚 परिवहन बुकिंग', book_transport:'ट्रांसपोर्ट बुक करें',
    name_label:'👤 नाम *', mobile_label:'📱 मोबाइल नंबर *', pickup_location_label:'📍 पिकअप स्थान *',
    crop_type_label:'🌾 फसल का प्रकार *', quantity_label:'⚖️ मात्रा (क्विंटल) *',
    pickup_date_label:'📅 पिकअप तारीख *', submit_booking:'📋 बुकिंग दर्ज करें',
    booking_status:'बुकिंग स्थिति', pending:'प्रतीक्षारत', accepted:'स्वीकृत',
    on_the_way:'रास्ते में', completed:'पूर्ण',
    share_whatsapp:'WhatsApp पर शेयर करें',
    disease_detect_title:'📸 फसल रोग पहचानें', disease_detect_desc:'फोटो अपलोड करें – रोग पता करेंगे',
    upload_photo:'फोटो अपलोड करें', back:'वापस',
    disease_detection:'🔬 रोग पहचान', upload_crop_photo:'फसल की फोटो अपलोड करें',
    disease_instructions:'रोगग्रस्त हिस्से की स्पष्ट तस्वीर लें',
    click_to_upload:'क्लिक करके फोटो चुनें', or_use_camera:'या कैमरा से सीधे लें',
    detected_disease:'संभावित रोग', confidence:'विश्वास स्तर:', treatment:'उपचार',
    ask_expert:'🧑‍🔬 विशेषज्ञ से पूछें', share_result:'परिणाम शेयर करें',
    notif_title:'सूचनाएं', profile_my_crops:'🌾 मेरी फसलें', profile_alerts:'🔔 मेरे अलर्ट',
    profile_history:'📋 बुकिंग इतिहास', profile_help:'❓ सहायता',
    footer_tagline:'किसानों का डिजिटल साथी', footer_about_us:'हमारे बारे में',
    about:'परिचय', contact:'संपर्क', help:'सहायता', privacy:'गोपनीयता',
    footer_services:'सेवाएं', footer_connect:'जुड़ें', helpline:'किसान हेल्पलाइन: 1800-180-1551',
    footer_copyright:'© 2025 AgroMitra | भारतीय किसानों के लिए बनाया गया 🇮🇳',
    share_whatsapp_text:'WhatsApp पर शेयर करें',
  },
  en: {
    nav_home:'Home', nav_crop:'Crop Library', nav_community:'Community', nav_mandi:'Mandi Rates', nav_transport:'Transport',
    hero_title:'AgroMitra – Your Digital Farming Partner',
    hero_desc:'Crop knowledge, market prices, expert advice & transport support – all in one place',
    search_placeholder:'Search crop, mandi or question...', search_btn:'Search',
    today_dashboard:"Today's Dashboard", weather:"Today's Weather", best_price:"Best Price Today",
    my_transport:'My Transport Booking', community_answers:'Latest Answers',
    see_all_rates:'See All Rates →', track_transport:'Track →', see_community:'View Community →',
    popular_crops:'Popular Crops', crop_library:'🌾 Crop Library', all:'All', kharif:'Kharif', rabi:'Rabi', zaid:'Zaid',
    crop_search_placeholder:'Search crop name...',
    community_qa:'💬 Farmer Community', ask_question:'+ Ask Question',
    all_crops:'All Crops', latest:'Latest', most_answered:'Most Answered',
    ask_question_title:'Ask a New Question', question_title_label:'Question Title *',
    select_crop_label:'Select Crop *', district_label:'District *', description_label:'Description',
    upload_image_label:'Upload Photo (Optional)', submit_question:'Submit Question',
    mandi_rates:'📊 Mandi Rates', all_districts:'All Districts',
    mandi_name:'Mandi Name', min_price:'Min Price', max_price:'Max Price', avg_price:'Avg Price',
    price_trend:'Price Trend – Last 7 Days', set_alert:'🔔 Set Price Alert',
    set_price_alert:'Set Price Alert', alert_price_label:'Alert Price (₹/quintal)', save_alert:'Save Alert',
    transport_request:'🚚 Transport Booking', book_transport:'Book Transport',
    name_label:'👤 Name *', mobile_label:'📱 Mobile Number *', pickup_location_label:'📍 Pickup Location *',
    crop_type_label:'🌾 Crop Type *', quantity_label:'⚖️ Quantity (Quintals) *',
    pickup_date_label:'📅 Pickup Date *', submit_booking:'📋 Submit Booking',
    booking_status:'Booking Status', pending:'Pending', accepted:'Accepted',
    on_the_way:'On the Way', completed:'Completed',
    share_whatsapp:'Share on WhatsApp',
    disease_detect_title:'📸 Detect Crop Disease', disease_detect_desc:'Upload crop photo – we detect disease & suggest treatment',
    upload_photo:'Upload Photo', back:'Back',
    disease_detection:'🔬 Disease Detection', upload_crop_photo:'Upload Crop Photo',
    disease_instructions:'Take a clear photo of the affected part of your crop',
    click_to_upload:'Click to choose photo', or_use_camera:'Or capture from camera',
    detected_disease:'Possible Disease', confidence:'Confidence:', treatment:'Treatment',
    ask_expert:'🧑‍🔬 Ask an Expert', share_result:'Share Result',
    notif_title:'Notifications', profile_my_crops:'🌾 My Crops', profile_alerts:'🔔 My Alerts',
    profile_history:'📋 Booking History', profile_help:'❓ Help',
    footer_tagline:"Farmer's Digital Partner", footer_about_us:'About Us',
    about:'About', contact:'Contact', help:'Help', privacy:'Privacy',
    footer_services:'Services', footer_connect:'Connect', helpline:'Farmer Helpline: 1800-180-1551',
    footer_copyright:'© 2025 AgroMitra | Made for Indian Farmers 🇮🇳',
    share_whatsapp_text:'Share on WhatsApp',
  },
  bh: {
    nav_home:'घरे', nav_crop:'फसल', nav_community:'समाज', nav_mandi:'मंडी भाव', nav_transport:'गाड़ी',
    hero_title:'AgroMitra – रउआ के खेती के साथी',
    hero_desc:'फसल जानकारी, मंडी भाव, सलाह आ गाड़ी सहायता – एके जगह',
    search_placeholder:'फसल, मंडी या सवाल खोजीं...', search_btn:'खोजीं',
    today_dashboard:'आज के डैशबोर्ड', weather:'आज के मौसम', best_price:'आज के बढ़िया भाव',
    my_transport:'हमार गाड़ी बुकिंग', community_answers:'नया जवाब',
    see_all_rates:'सब भाव देखीं →', track_transport:'ट्रैक करीं →', see_community:'समाज देखीं →',
    popular_crops:'मशहूर फसल', crop_library:'🌾 फसल सूची', all:'सब', kharif:'खरीफ', rabi:'रबी', zaid:'जायद',
    crop_search_placeholder:'फसल के नाम खोजीं...',
    community_qa:'💬 किसान समाज', ask_question:'+ सवाल पूछीं',
    all_crops:'सब फसल', latest:'नया', most_answered:'सबसे ज्यादा जवाब',
    ask_question_title:'नया सवाल पूछीं', question_title_label:'सवाल के शीर्षक *',
    select_crop_label:'फसल चुनीं *', district_label:'जिला *', description_label:'विवरण',
    upload_image_label:'फोटो अपलोड (वैकल्पिक)', submit_question:'सवाल दर्ज करीं',
    mandi_rates:'📊 मंडी भाव', all_districts:'सब जिला',
    mandi_name:'मंडी के नाम', min_price:'कम भाव', max_price:'ज्यादा भाव', avg_price:'औसत भाव',
    price_trend:'पिछला 7 दिन के भाव', set_alert:'🔔 भाव अलर्ट लगाईं',
    set_price_alert:'भाव अलर्ट लगाईं', alert_price_label:'अलर्ट भाव (₹/क्विंटल)', save_alert:'अलर्ट सेव करीं',
    transport_request:'🚚 गाड़ी बुकिंग', book_transport:'गाड़ी बुक करीं',
    name_label:'👤 नाम *', mobile_label:'📱 मोबाइल नंबर *', pickup_location_label:'📍 पिकअप जगह *',
    crop_type_label:'🌾 फसल के प्रकार *', quantity_label:'⚖️ मात्रा (क्विंटल) *',
    pickup_date_label:'📅 पिकअप तारीख *', submit_booking:'📋 बुकिंग दर्ज करीं',
    booking_status:'बुकिंग हाल', pending:'इंतजार में', accepted:'मंजूर', on_the_way:'रस्ता में', completed:'पूरा',
    share_whatsapp:'WhatsApp पे शेयर करीं',
    disease_detect_title:'📸 फसल रोग पहचानीं', disease_detect_desc:'फोटो अपलोड करीं – रोग बतइबो',
    upload_photo:'फोटो अपलोड करीं', back:'वापस',
    disease_detection:'🔬 रोग पहचान', upload_crop_photo:'फसल के फोटो अपलोड करीं',
    disease_instructions:'रोगी हिस्से के साफ तस्वीर लीं',
    click_to_upload:'क्लिक क के फोटो चुनीं', or_use_camera:'या कैमरा से लीं',
    detected_disease:'संभावित रोग', confidence:'भरोसा:', treatment:'इलाज',
    ask_expert:'🧑‍🔬 विशेषज्ञ से पूछीं', share_result:'नतीजा शेयर करीं',
    notif_title:'सूचना', profile_my_crops:'🌾 हमार फसल', profile_alerts:'🔔 हमार अलर्ट',
    profile_history:'📋 बुकिंग इतिहास', profile_help:'❓ मदद',
    footer_tagline:'किसान के डिजिटल साथी', footer_about_us:'हमार बारे में',
    about:'परिचय', contact:'संपर्क', help:'मदद', privacy:'गोपनीयता',
    footer_services:'सेवाएं', footer_connect:'जुड़ीं', helpline:'किसान हेल्पलाइन: 1800-180-1551',
    footer_copyright:'© 2025 AgroMitra | भारतीय किसानन खातिर बनावल 🇮🇳',
    share_whatsapp_text:'WhatsApp पे शेयर करीं',
  }
};
